### ISSUE TITLE
Tensor Size mismatch error

### ISSUE THREAD

**Issue by TinyTerra** [BlenderNeko/ComfyUI_ADV_CLIP_emb#5]
Getting the following error using Advanced Clip node:

Normalization: none, Interpretation: Comfy++

> got prompt
Traceback (most recent call last):
  File "T:\AI\Comfy\ComfyUI\execution.py", line 195, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "T:\AI\Comfy\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "T:\AI\Comfy\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\nodes.py", line 19, in encode
    embeddings_final = advanced_encode(clip, text, token_normalization, weight_interpretation, w_max=1.0)
  File "T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 193, in advanced_encode
    return advanced_encode_from_tokens(clip, tokenized, token_normalization, weight_interpretation, w_max)
  File "T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 183, in advanced_encode_from_tokens
    weighted_emb = from_masked(unweighted_tokens, weights, word_ids, weighted_emb, clip)
  File "T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 87, in from_masked
    embs = batched_clip_encode(masked_tokens, clip, len(tokens))
  File "T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb\adv_encode.py", line 54, in batched_clip_encode
    embs = torch.cat(embs)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2464 but got size 1540 for tensor number 1 in the list.

Prompt:
> (RAW photo:1.2), wide angle, perfect composition, 1 woman(upper body selfie, happy), masterpiece, best quality, ultra-detailed, solo, outdoors, (night), mountains, nature, (stars, moon) cheerful, happy, backpack, sleeping bag, camping stove, water bottle, mountain boots, gloves, sweater, hat, flashlight, forest, rocks, river, wood, smoke, shadows, contrast, clear sky, analog style (look at viewer:1.2) (skin texture) (film grain:1.3), (warm hue, warm tone), close up, cinematic light, sidelighting, ultra high res, best shadow, RAW, upper body, wearing pullover, (masterpiece, 8k, absurdres, best quality, intricate), realistic, raytracing, dramatic light,

**Comment by BlenderNeko** [comment]
this sounds like #2, git pull and try again

**Comment by TinyTerra** [comment]
I'm sure I had already tried that... But yeah, this time it worked. Cheers
